const _CELL_SIZE = 20;
const CSSCLASSFOR_OUR_TANK = "cellWithOurTank";
//вот три класса, в которых бэкграундзадает разные направления   танка
const CSSCLASSFOR_TO_TOP = "ToTop";
const CSSCLASSFOR_TO_BOTTOM = "ToBottom";
const CSSCLASSFOR_TO_LEFT = "ToLeft";
const CSSCLASSFOR_TO_RIGHT = "ToRight";
const CSSCLASSFOR_ENEMY_TANK = "cellWithEnemyTank";
const CSSCLASSFOR_ENEMY_TANK_DAMAGED = "cellWithEnemyTankDamaged";
export {_CELL_SIZE, CSSCLASSFOR_OUR_TANK, CSSCLASSFOR_TO_TOP, CSSCLASSFOR_TO_BOTTOM, CSSCLASSFOR_TO_LEFT, CSSCLASSFOR_TO_RIGHT, CSSCLASSFOR_ENEMY_TANK, CSSCLASSFOR_ENEMY_TANK_DAMAGED};